### ISSUE TITLE
should the contract make the project no subgraph needed?

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/primary-pfp-contract#27]
looks like if the contract save all the data to make frontend not subgraph needed, the frontend can be a IPFS version and no maintain fee for that? 

which means we can make the project charge no fee and make it decentralized by a long time registered ENS?

if the contract provide `address[] getCommunityContracts()` and `address[] getCommunityPrimaryAddresses(address collectionContract_)`, can the frontend make it 0 dependency to subgraph?

what do you think @0xtiby

**Comment by PirateCode-eth** [comment]
if this project just provide the onchain data, no need to save these data, anyone want to build product based on these data can build their own subgraph service.

if the project want to provide the utility connecting twitter accounts by setting primary PFP most decentralized way, then it can be designed like this to provide more data.

if this project is going to build onchain social networking product to replace twitter, make the contract upgradeable & payment is a must.

**Comment by 0xtiby** [comment]
I think the use of 3rd party help to have a better ux. But having all the data needed on chain is very good to let people build product around it.

**Comment by PirateCode-eth** [comment]
Got it, so we keep contract remain without saving extra data and make it as simple as possible.

**Comment by PirateCode-eth** [comment]
It's a trade off, add these two functions cost a lot more gas for storage, if payable is for subgraph cost, keep both payable and cost gas by saving these data looks like not good?

**Comment by 0xtiby** [comment]
Yes, you'r right. Let's make it paybale with subgraph and other services.

**Comment by PirateCode-eth** [comment]
OK.

**Comment by PirateCode-eth** [comment]
@0xtiby I rechecked this issue, and after review the code from delegate.cash, I will try to make a version with all the data onchain, and a gas cost compare for this, making subgraph for these two functions seems like too complicated.

**Comment by PirateCode-eth** [comment]
this is the gas before implements those two functions, will update the gas report after the implementation:
![image](https://github.com/ForeverPFP/primary-pfp-contract/assets/110432670/dbafa934-391e-44a8-8694-178b23765188)

**Comment by PirateCode-eth** [comment]
PR merged: https://github.com/ForeverPFP/primary-pfp-contract/pull/47
