### ISSUE TITLE
should remove payment for setPrimary

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/primary-pfp-contract#36]
once the project is independent, the payment in primary PFP looks not good design, the payment are supposed to be for the social app(tmp name ForeverPFP) build on primary PFP + primary ENS + ENS content for twitter account + mirror.xyz etc.

So remove payment from primary PFP?

@0xtiby

**Comment by 0xtiby** [comment]
Ok, but how to finance the social app ?

**Comment by PirateCode-eth** [comment]
Won't be hard, make a register mapping onchain like 0.01e for one year and query that registration before sign by Ethereum address. 

The key point is make as many people set primary PFP as possible, it better to be free, social app need to be paid cos it build on different components of web3.

**Comment by PirateCode-eth** [comment]
the same thing happened for delegate.cash, delegation contract is free to use, but footbar build business on delegate.cash that can make money.

**Comment by 0xtiby** [comment]
Ok I understand.
