### ISSUE TITLE
add delegate.cash & warm.xyz support

### ISSUE THREAD

**Issue by PirateCode-eth** [ForeverPFP/primary-pfp-contract#43]
talked to some web3 people, they suggested to support delegate.cash & warm.xyz, which risk 0 for they NFT in vault.

I think it's cool, if a user delegated a ERC721 PFP to one hotwallet address A, use A to set primary PFP is easy? 

what do you think @0xtiby

**Comment by 0xtiby** [comment]
Yes, good idea. I think for me this change nothing to set the delegated address. But on the contract side you will need to update it to check the delegate ? I have used delegate.cash but never warm.xyz

**Comment by PirateCode-eth** [comment]
the interfaces before don't need to change, but I will add two more functions for: 
```
     /**
     * @notice Set primary PFP for an address from a delegated address from delegate.cash.
     * Only the delegated address from delegate cash can set it.
     *
     * @param contract_ The collection address of the PFP
     * @param tokenId The tokenId of the PFP
     */
    function setPrimaryByDelegateCash(
        address contract_,
        uint256 tokenId
    ) external;

    /**
     * @notice Set primary PFP for an address from a warmed address from warm.xyz.
     * Only the warmed address from warm.xyz can set it.
     *
     * @param contract_ The collection address of the PFP
     * @param tokenId The tokenId of the PFP
     */
    function setPrimaryByWarmXyz(address contract_, uint256 tokenId) external;
```
